$(DIR_OBJS)/is/ft_isalnum.o $(DIR_OBJS)/is/ft_isalpha.o \
				$(DIR_OBJS)/is/ft_isascii.o $(DIR_OBJS)/is/ft_isdigit.o \
				$(DIR_OBJS)/is/ft_isprint.o $(DIR_OBJS)/is/ft_isspace.o \
				$(DIR_OBJS)/to/ft_atoi.o $(DIR_OBJS)/to/ft_itoa.o \
				$(DIR_OBJS)/to/ft_tolower.o $(DIR_OBJS)/to/ft_toupper.o \
				$(DIR_OBJS)/mem/ft_bzero.o $(DIR_OBJS)/mem/ft_calloc.o \
				$(DIR_OBJS)/mem/ft_memchr.o $(DIR_OBJS)/mem/ft_memcmp.o \
				$(DIR_OBJS)/mem/ft_memcpy.o $(DIR_OBJS)/mem/ft_memmove.o \
				$(DIR_OBJS)/mem/ft_memset.o \
				$(DIR_OBJS)/put/ft_putchar_fd.o $(DIR_OBJS)/put/ft_putendl_fd.o \
				$(DIR_OBJS)/put/ft_putnbr_fd.o $(DIR_OBJS)/put/ft_putstr_fd.o \
				$(DIR_OBJS)/str/ft_split.o $(DIR_OBJS)/str/ft_strchr.o \
				$(DIR_OBJS)/str/ft_strdup.o $(DIR_OBJS)/str/ft_striteri.o \
				$(DIR_OBJS)/str/ft_strjoin.o $(DIR_OBJS)/str/ft_strlcat.o \
				$(DIR_OBJS)/str/ft_strlcpy.o $(DIR_OBJS)/str/ft_strlen.o \
				$(DIR_OBJS)/str/ft_strmapi.o $(DIR_OBJS)/str/ft_strncmp.o \
				$(DIR_OBJS)/str/ft_strnstr.o $(DIR_OBJS)/str/ft_strrchr.o \
				$(DIR_OBJS)/str/ft_strtrim.o $(DIR_OBJS)/str/ft_substr.o \
				$(DIR_OBJS)/lst/ft_lstadd_back_bonus.o \
				$(DIR_OBJS)/lst/ft_lstadd_front_bonus.o \
				$(DIR_OBJS)/lst/ft_lstclear_bonus.o \
				$(DIR_OBJS)/lst/ft_lstdelone_bonus.o \
				$(DIR_OBJS)/lst/ft_lstiter_bonus.o \
				$(DIR_OBJS)/lst/ft_lstlast_bonus.o \
				$(DIR_OBJS)/lst/ft_lstnew_bonus.o \
				$(DIR_OBJS)/lst/ft_lstsize_bonus.o \
				$(DIR_OBJS)/gnl/ft_get_next_line_utils.o \
				$(DIR_OBJS)/gnl/ft_get_next_line.o \
				$(DIR_OBJS)/printf/ft_print_format.o $(DIR_OBJS)/printf/ft_printf.o